from __future__ import annotations

import json
from pathlib import Path

from src.storage.event_repository import list_alerts, list_events
from src.utils.config_loader import load_config, resolve_project_path
from src.utils.time_utils import utc_now_iso


def build_session_report(session_id: str) -> dict[str, object]:
    events = list_events(session_id)
    alerts = list_alerts(session_id)
    highest_score = max([int(alert["risk_score"]) for alert in alerts], default=0)
    return {
        "session_id": session_id,
        "generated_at": utc_now_iso(),
        "event_count": len(events),
        "alert_count": len(alerts),
        "highest_risk_score": highest_score,
        "events": events,
        "alerts": alerts,
        "prototype_note": "This report is generated by a research prototype. AI alerts support human review and do not declare misconduct automatically.",
    }


def export_session_report_json(session_id: str) -> Path:
    config = load_config()
    export_dir = resolve_project_path(config["storage"]["export_dir"])
    export_dir.mkdir(parents=True, exist_ok=True)
    path = export_dir / f"{session_id}_report.json"
    with path.open("w", encoding="utf-8") as handle:
        json.dump(build_session_report(session_id), handle, indent=2, default=str)
    return path
