from __future__ import annotations

import json
from pathlib import Path

from src.evaluation.viva_scenarios import list_viva_scenario_runs
from src.policy.incident_repository import list_policy_decisions
from src.storage.event_repository import list_alerts, list_events
from src.utils.config_loader import load_config, resolve_project_path
from src.utils.time_utils import utc_now_iso


def build_session_report(session_id: str) -> dict[str, object]:
    events = list_events(session_id)
    alerts = list_alerts(session_id)
    policy_decisions = list_policy_decisions(session_id)
    scenario_runs = list_viva_scenario_runs(session_id)
    highest_score = max([int(alert["risk_score"]) for alert in alerts], default=0)
    return {
        "session_id": session_id,
        "generated_at": utc_now_iso(),
        "event_count": len(events),
        "alert_count": len(alerts),
        "policy_decision_count": len(policy_decisions),
        "viva_scenario_run_count": len(scenario_runs),
        "highest_risk_score": highest_score,
        "report_sections": [
            "raw_evidence_events",
            "contextual_alerts",
            "institutional_policy_decisions",
            "viva_scenario_validation",
            "human_review_trace",
        ],
        "events": events,
        "alerts": alerts,
        "policy_decisions": policy_decisions,
        "viva_scenario_validation": scenario_runs,
        "evidence_pack_manifest": [
            {
                "decision_id": decision.get("decision_id"),
                "alert_id": decision.get("alert_id"),
                "candidate_id": decision.get("candidate_id"),
                "risk_level": decision.get("risk_level"),
                "workflow_label": decision.get("workflow_label"),
                "status": decision.get("status"),
                "acknowledgement_required": decision.get("require_acknowledgement"),
                "preserve_evidence": decision.get("preserve_evidence"),
            }
            for decision in policy_decisions
        ],
        "due_process_note": (
            "SERPS records potential examination integrity concerns for authorised human review. "
            "The report does not declare misconduct."
        ),
        "human_review_boundary": "Final examination integrity decisions remain with authorised human reviewers.",
        "prototype_note": "This report is generated by a research prototype. AI alerts support human review and do not declare misconduct automatically.",
    }


def export_session_report_json(session_id: str) -> Path:
    config = load_config()
    export_dir = resolve_project_path(config["storage"]["export_dir"])
    export_dir.mkdir(parents=True, exist_ok=True)
    path = export_dir / f"{session_id}_report.json"
    with path.open("w", encoding="utf-8") as handle:
        json.dump(build_session_report(session_id), handle, indent=2, default=str)
    return path
